---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: docker build mynginx
      docker_image:
        name: mynginx
        tag: '20'
        build:
          path: all_images/nginx/
        source: build
